version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sniper_app
    env_file:
      - .env
    environment:
      # FastAPI app config
      SNIPER_CONFIG_PATH: /app/config/config.yaml
      # Database credentials consumed by the app
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15-alpine
    container_name: sniper_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: sniper_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: sniper_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
